[build]
  command = "gatsby build5"
  publish = "public/"

[template.environment]
  GATSBY_FLOTIQ_API_KEY="YOUR FLOTIQ API KEY"

[build.environment]
  GATSBY_FLOTIQ_API_KEY = "YOUR FLOTIQ API KEY"

[context.production]
  [context.production.environment]
    GATSBY_FLOTIQ_API_KEY = "super secret"
